### ISSUE TITLE
Bluepy fails to start on pi3

### ISSUE THREAD

**Issue by MACscr** [jshridha/inkbird#21]
```
root@raspberrypi:~# docker-compose up
Starting root_inkbird_1 ... done
Attaching to root_inkbird_1
inkbird_1  | 2022-07-12 11:09:25,709 inkbird      INFO     Connecting to 49:42:08:00:57:CF
inkbird_1  | Traceback (most recent call last):
inkbird_1  |   File "main.py", line 26, in <module>
inkbird_1  |     client.connect()
inkbird_1  |   File "/usr/src/app/inkbird/client.py", line 87, in connect
inkbird_1  |     self.characteristics[0].getHandle() + 1, b"\x01\x00", withResponse=True
inkbird_1  |   File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
inkbird_1  |     return self._getResp('wr')
inkbird_1  |   File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 407, in _getResp
inkbird_1  |     resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
inkbird_1  |   File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 368, in _waitResp
inkbird_1  |     raise BTLEGattError("Bluetooth command failed", resp)
inkbird_1  | bluepy.btle.BTLEGattError: Bluetooth command failed (code: 3, error: Attribute can't be written)
root_inkbird_1 exited with code 1
root@raspberrypi:~# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@raspberrypi:~# uptime
 12:10:10 up 14 days, 12:04,  1 user,  load average: 0.06, 0.10, 0.31
root@raspberrypi:~# uname -a
Linux raspberrypi 5.15.45-v7+ #1561 SMP Mon Jun 6 15:21:44 BST 2022 armv7l GNU/Linux
root@raspberrypi:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@raspberrypi:~# bluetoothctl
Agent registered
[bluetooth]# list
Controller B8:27:EB:14:9A:72 raspberrypi [default]
```

**Comment by MACscr** [comment]
btw, I have a IBS-TH2 that does humidity and temperature. will it by chance pass both values?
